---
services:
  xhrec:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: xhrec
    restart: unless-stopped
    ports:
      - 8090:8090
    dns:
      - 9.9.9.9
      - 149.112.112.112
    dns_opt:
      - no-aaaa
    environment:
      - TZ=America/Chicago  # Update to your local time zone
    volumes:
      # Mount configuration files/templates directory
      - ./config:/app/config
      # Mount directory where recorded video streams are saved
      - ./recordings:/app/recordings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
